# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: TeepSmart
email: your-email@domain.com
author: Clark Teeple
description: > # "Write an awesome description for your new site here. 
  Reed Pro. Your next reed is not a reed.
copyright: 'Copyright &copy; 2020 TeepSmart Inc. All Rights Reserved.'
credits: This website is definitely not a parody of the <a target="_blank" href="https://www.apple.com/ipad-pro/">iPad Pro</a>... 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Store
    fa: fa fa-tag
    url: http://www.cbteeple.com
