# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://yoursite.com
title: TeepSmart
email: your-email@domain.com
author: Clark Teeple
description: > # "Write an awesome description for your new site here. 
  Reed Pro. Your next reed is not a reed.
copyright: 'Copyright &copy; 2020 TeepSmart Inc. All Rights Reserved.'
credits:

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Store
    url: https://cbteeple.com
